# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwzKUKFHpLdA9lI7VZXppgPZo2TJMdp5
"""

from bs4 import BeautifulSoup
import requests
import pandas as pd


book_name = []
prices = []
ratings = []
instock = []


for i in range(1, 12):
    url = f'https://books.toscrape.com/catalogue/page-{i}.html'
    response = requests.get(url)
    response.encoding = 'utf-8'
    content = response.text
    soup = BeautifulSoup(content, 'html.parser')

#Book names
    names = soup.find_all('h3')
    for n in names:
        book_name.append(n.text)
    #  print(book_name)

#Prices
    price = soup.find_all('p', class_='price_color')
    for p in price:
        prices.append(p.text)
    # print(prices)

#Ratings
    rating = soup.find_all('p', class_='star-rating')
    for r in rating:
        rating_class = r['class'][1]
        ratings.append(rating_class)
    # print(ratings)

#Availability
    availability = soup.find_all('p', class_='instock availability')
    for a in availability:
        instock.append(a.text.strip())
    # print(instock)

#create a DataFrame
df = pd.DataFrame({
    "Book Name": book_name,
    "Book Price": prices,
    "Ratings": ratings,
    "Availability": instock
})

#Print the DataFrame
print(df)

df.to_csv('Books.csv')

